### ISSUE TITLE
IPv6 support for the DNS lookup

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/is-online#15]
The node version currently only tries to contact the root servers over IPv4. It would be nice if IPv6 would be used as a fallback if IPv4 is unavailable.

`roots("AAAA")` can be used to retrieve an array of IPv6 addresses of the root servers. Unfortunately, I don't have pure IPv6 available from my ISP, so I can't test reliably.

**Comment by sindresorhus** [comment]
So currently it would fail if the user on a IPv6 only connection, right?

**Comment by silverwind** [comment]
Yes, pure IPv6 can only reach other IPv6 hosts. Such a connection is probably very rare today.

**Comment by sindresorhus** [comment]
Alright, if do a PR I'll find someone with a pure IPv6 connection to test.

**Comment by silverwind** [comment]
Should be possible on a dual stack setup of you remove the IPv4 from the interface.

**Comment by silverwind** [comment]
Also, www.baidu.com and www.yandex.ru do not have AAAA records, so they aren't suitable for IPv6.

**Comment by sindresorhus** [comment]
> Also, www.baidu.com and www.yandex.ru do not have AAAA records, so they aren't suitable for IPv6.

I'm sure we could find a popular Chinese and Russian website with IPv6.

**Comment by silverwind** [comment]
Yandex gained v6 support, so it's just baidu, who do offer it on a separate domain it seems, `ipv6.baidu.com`.

**Comment by seesemichaelj** [comment]
Hey @sindresorhus, @dweremeichik and I maintain a repo which uses your package (https://github.com/nylas-mail-lives/nylas-mail). We kind of inherited it from a company that stopped supporting it. It looks like we're using v7.0.0 of your package and I believe that should incorporate fixes for this issue, but one of our users is noticing issues with is-online succeeding under IPv6 but has no issues with IPv4.

Before we dig deeper, I just wanted to verify with you that you expect this to be working for sole IPv6 users? Thanks!

**Comment by seesemichaelj** [comment]
It seems that this may have not added a fallback option if IPv4 fails, but rather just add an IPv6 option if the user wants it (see https://github.com/sindresorhus/is-online/pull/39/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9R44). With this said, I would think the concept of `is-online` is to default to the more intensive "for sure" check to see if they're online (i.e. try IPv6 if IPv4 fails) rather than have the developer check if IPv4 fails and then do a IPv6 check; seems a bit much if the point is to just check if you're online haha. Someone at our repo would be responsible for writing the issue/PR to make this happen if you're interested; otherwise we'll do it on the client/dev end
