### ISSUE TITLE
Apple captive portal check

### ISSUE THREAD

**Issue by jish** [sindresorhus/is-online#72]
Hello,

I was reading through your readme and I was curious what you meant by "Retrieve Apple's Captive Portal test page" https://github.com/sindresorhus/is-online/blob/936f3fe354fee3e3bfa80874263e292c40b97524/readme.md#how-it-works

So, I checked in the source code https://github.com/sindresorhus/is-online/blob/936f3fe354fee3e3bfa80874263e292c40b97524/index.js#L19-L20

It looks like, if the string `"Success"` is present then a new `Error` is thrown. I'm confused how the success case works for this captive portal request 🤔 Could you help me understand?

Do you think it would be helpful to add some documentation around the Apple Captive Portal test page?

**Comment by sindresorhus** [comment]
I think this is a bug that was introduced in https://github.com/sindresorhus/is-online/commit/034907786aa4df0dbba6a3346163d346e3721304.

// @LuKks

**Comment by LuKks** [comment]
> Could you help me understand?

The success check was in the opposite direction:

```js
if (body && body.includes('Success')) {
```
->
```js
if (!body || !body.includes('Success')) {
```

> Do you think it would be helpful to add some documentation around the Apple Captive Portal test page?

No no, it was just a wrong condition.
It would be awesome if the test checks for the resulted boolean (which should be `true`), because I ran tests before submitting the pull request that caused the bug and everything was ok.
Also, silly of me that didn't see that little wrong condition, I think I was moving some code and I didn't notice it.
