### ISSUE TITLE
Why do you use http protocol for apple's captive website?

### ISSUE THREAD

**Issue by ProgrammingLife** [sindresorhus/is-online#74]
Maybe it's better to use https version?
How often can I check isOnline status using this lib?

**Comment by sindresorhus** [comment]
@silverwind Do you remember why we use HTTP and not HTTPS for that?

**Comment by sindresorhus** [comment]
> How often can I check isOnline status using this lib?

As often as you want, but if you check too often, you're just wasting resources.

**Comment by silverwind** [comment]
IIRC, the service did not support HTTPS when the check was implemented, but it seems it now does:

```
$ curl https://captive.apple.com/hotspot-detect.html
<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>
$ curl https://captive.apple.com/hotspot-detect.html
<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>

**Comment by silverwind** [comment]
On second thought, I think it's specifically using HTTP because router interception only works for HTTP, not HTTPS (it can not offer a valid certificate unless one is pre-installed on the machine).

Still I think using HTTPS should be preferred. With it, the check will fail at either the connection or certificate verification stage when not online.
